### ISSUE TITLE
Support for SASS and Less?

### ISSUE THREAD

**Issue by forabi** [csstree/vscode-plugin#2]
Can this plugin validate Sass/Less files?

**Comment by smelukov** [comment]
Not yet, unfortunately.
Before we can support SASS/Less there is some work to do

**Comment by smelukov** [comment]
Close the issue cause it's all about https://github.com/csstree/csstree

**Comment by forabi** [comment]
I ended up using csstree as a stylelint plugin. VS Code already has as stylelint plugin so I got validation as I type in VS Code :smile:
