### ISSUE TITLE
csstree error(for iPhone X). Please confirm :)

### ISSUE THREAD

**Issue by FE-jw** [csstree/vscode-plugin#4]
#selector{right:0;right:constant(safe-area-inset-right);right:env(safe-area-inset-right);}

"right:constant(safe-area-inset-right);right:env(safe-area-inset-right)" is property for iPhone X.

error 1 : [CSSTree]Invalid value for 'right'
error 2 : [CSSTree]Invalid value for 'right'

**Comment by smelukov** [comment]
Thanks for the issue.
We created a related issue in csstree-repo - https://github.com/csstree/csstree/issues/90

**Comment by smelukov** [comment]
I'll close this issue cause this is not related to vscode-plugin directly
